#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use Minicli\App;


if (file_exists(__DIR__ . '/settings.php')) {
    $settings = include(__DIR__ . '/settings.php');
} else {
    die(
        "\nNo settings file found.\n"
        . "Please rename settings-rename.php to settings.php\n"
        . "and edit it to change all settings.\n\n"
    );
}


$app = new App([
    'app_path' => __DIR__ . '/src/Command',
    'debug' => false,
    'settings' => $settings
]);

$app->setSignature("TwitchBot for Twitch.\n./twitchbot twitch");
if (!is_array($argv) || count($argv) == 1) {
    $app->runCommand(array('./twitchbot', 'twitch'));
    exit;
}
$app->runCommand($argv);
