#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use Minicli\App;

$app = new App([
    'app_path' => __DIR__ . '/src/Command',
    'debug' => false,
    #Twitch
    'twitch_user' => '',
    'twitch_oauth' => '',
    'twitch_channel' => ''
]);

$app->setSignature("TwitchBot for Twitch.\n./twitchbot twitch");
if (!is_array($argv) || count($argv) == 1) {
    $app->runCommand(array('./twitchbot', 'twitch'));
    exit;
}
$app->runCommand($argv);
